### ISSUE TITLE
Something's not right with redis://

### ISSUE THREAD

**Issue by peterbe** [pmac/urlwait#4]
```
root@a83acbc94d5a:/app# urlwait redis://redis:6379/0 10
root@a83acbc94d5a:/app# echo $?
0
```
makes sense. Because I know it's running there on that port. 

However, if I typo the URL it does not break. 
```
root@a83acbc94d5a:/app# urlwait redis://redis:63799999999/0 10
root@a83acbc94d5a:/app# echo $?
0
```

**Comment by peterbe** [comment]
Hmm... My above example comes from usage of `urlwait` inside docker-compose from github.com/mozilla/kuma which uses Python 2.7. It uses urlwait==0.4 which is the [latest on PyPI](https://pypi.org/project/urlwait/#history).

But I cloned the repo, created a Python 3.7 virtualenv and tried:

```
▶ urlwait redis://127.0.0.1:6379/0
(urlwait)
▶ echo $?
0
```
Now, to break it (:9379 instead of :6379):
```
▶ urlwait redis://127.0.0.1:9379/0 10
Could not connect to redis://127.0.0.1:9379/0
```

**Comment by peterbe** [comment]
Tried again with a fresh Python 2.7 virtualenv:
```
▶ urlwait redis://127.0.0.1:9379/0 10
Could not connect to redis://127.0.0.1:9379/0
▶ echo $?
1
```

**Comment by peterbe** [comment]
What the heck! Now it's not happening in Docker either. I don't know how or why but the problem appears to have gone away. Trying to understand what I did wrong/differently.

**Comment by peterbe** [comment]
Ok. I think I see what's going on. `urlwait redis://redis:63799999999/0 10` was perhaps the wrong test. Or rather, it should still have failed:
```
▶ urlwait redis://127.0.0.1:63799999999/0 10
▶ echo $?
0
```

**Comment by peterbe** [comment]
I did some print debugging. If you use `redis://redis:63799999999/0` and print `(self.host, self.port)` it prints:
```
127.0.0.1 6379
```

**Comment by peterbe** [comment]
This kinda explains it:
```
>>> import urlparse
>>> print urlparse.urlparse('redis://127.0.0.1:6379').port
6379
>>> print urlparse.urlparse('redis://127.0.0.1:637999999').port
None
```

**Comment by pmac** [comment]
ah! so it was outside of the range of possible port values. Perhaps we should be failing in that case with a useful message?

**Comment by peterbe** [comment]
My usecase was extreme and probably not worth the mental energy to worry about.
